# volumes:
volumes:
  anchor-postgres-data:
    external: true
  pg-admin:
    external: true

services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - anchor-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: account,blog,listing
      POSTGRES_PASSWORD: test-databases
    ports:
      - 15432:5432
  # fastapi:
  #   build:
  #     context: sample_service
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./sample_service:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      # REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
      REACT_APP_BLOG_SERVICE: http://localhost:8080
      REACT_APP_LISTING_SERVICE: http://localhost:8090
      REACT_APP_ACCOUNT_SERVICE: http://localhost:8100

  blog_service:
    build:
      context: ./blog_service
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./blog_service:/app
    environment:
      DATABASE_URL: postgresql://blog:password@postgres/blog
      WAIT_HOSTS: postgres:5432

  listing_service:
    build:
      context: ./listing_service
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./listing_service:/app
    environment:
      DATABASE_URL: postgresql://listing:password@postgres/listing
      WAIT_HOSTS: postgres:5432

  account_service:
    build:
      context: ./account_service
      dockerfile: ./Dockerfile.dev
    ports:
      - "8100:8000"
    volumes:
      - ./account_service:/app
    environment:
      DATABASE_URL: postgresql://account:password@postgres/account
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: ${SIGNING_KEY}

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1

